logging:
  file: /tmp/logs/app.log

management:
  address: 127.0.0.1
  endpoints:
    shutdown:
      enabled: true

server:
  tomcat:
    basedir: target/tomcat
    access_log_pattern: '%h %t "%r" %s %b'

security:
  require_ssl: false

service:
  name: Phil

shell:
  ssh:
    enabled: true
    port: 2222
  auth: spring



spring:
  jmx:
    enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
